[package]
authors = ["fuyutarow <fuyutarow@gmail.com>"]
edition = "2021"
license = "CC0-1.0"
name = "alds-lib"
version = "0.202203.0"

[lib]
name = "alds_lib"

[dependencies]
itertools = "=0.9.0"
num = "=0.2.1"
num-traits = "=0.2.11"
rand = {version = "=0.7.3", features = ["small_rng"]}
